config/routes.rb
Rails.application.routes.draw do
  root 'root#index'
  get 'counter', to: 'root#counter'
  get 'gauge', to: 'root#gauge'
  get 'histogram', to: 'root#histogram'
  get 'summary', to: 'root#summary'
  get 'error', to: 'root#error'
  get 'fnf', to: 'root#fnf'
  get 'prometheus', to: 'root#prometheus'
  get 'grafana', to: 'root#grafana'
  get 'alert_manager', to: 'root#alert_manager'
  get 'kubernetes_dashboard', to: 'root#kubernetes_dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  include Promethean::Controller

  def alert_manager
    redirect_to ENV['ALERT_MANAGER']
  end

  # Counter is a metric that exposes merely a sum or tally of things.
  def counter
    COUNTER_EXAMPLE
      .increment service: 'GiftCardService'
    # Next query the counter for a given label set
    @counter_value = COUNTER_EXAMPLE
                       .get service: 'GiftCardService'
  end

  # A route that raises a 500 :(((((((
  def error
    # Logging exception handling
    # Logging backtrace / context info
    respond_to do |f|
      f.any do
        render json: {
                 error: "An error has occured. Server administrators have been alerted.",
               }, status: 500
      end
    end
  end

  # A route that raises a fo'oh'fo - file not found
  def fnf
    respond_to do |f|
      f.any do
        render json: {
                 error: "File Not Found",
               }, status: 404
      end
    end
  end

  # Gauge is a metric that exposes merely an instantaneous value or some snapshot thereof.
  def gauge
    GAUGE_EXAMPLE
      .set({vehicle: :fastest_speed_boat}, Random.rand * 9000 * 2)
    @gauge_value = GAUGE_EXAMPLE
                     .get vehicle: :fastest_speed_boat
  end

  def grafana
    redirect_to ENV['GRAFANA']
  end

  # A histogram samples observations (usually things like request durations or response sizes) and counts
  # them in configurable buckets. It also provides a sum of all observed values.
  def histogram
    # Record a value
    @new_value = Random.rand
    HISTOGRAM_EXAMPLE.observe({service: :jumping_users}, @new_value)
    # Retrieve the current bucketed values
    @observations = HISTOGRAM_EXAMPLE.get(service: :jumping_users)
  end

  def index; end

  def kubernetes_dashboard
    redirect_to ENV['KUBERNETES_DASHBOARD']
  end

  def prometheus
    redirect_to ENV['PROMETHEUS']
  end

  # Summary, similar to histograms, is an accumulator for samples.
  # It captures Numeric data and provides an efficient percentile calculation mechanism.
  def summary
    @new_value = Random.rand * 100
    SUMMARY_EXAMPLE.observe({service: :test_scores_users}, @new_value)
    @observations = SUMMARY_EXAMPLE.get(service: :test_scores_users)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="jumbotron">
    <%= yield %>
  </body>
</html>

app/views/root/_back.erb
<%= link_to "Index", root_path %>

app/views/root/counter.html.erb
<% provide(:title, "Counter") %>
<%= render partial: 'back' %>
<h1>Counter</h1>
<p>Counter is a metric that exposes merely a sum or tally of things.</p>

<dl>
  <dd><b>@counter_value = </b> <%= @counter_value%></dd>
</dl>

<pre style='color:#000000;background:#f1f0f0;'><span style='color:#400000; font-weight:bold; '>def</span> counter
  COUNTER_EXAMPLE
    <span style='color:#806030; '>.</span>increment <span style='color:#005fd2; '>service</span>: <span style='color:#e60000; '>'GiftCardService'</span><span style='color:#806030; '>,</span>
               <span style='color:#005fd2; '>arbitrary</span>: <span style='color:#e60000; '>'key-value pairs'</span>
  <span style='color:#c34e00; '># Next query the counter for a given label set</span>
  @counter_value <span style='color:#806030; '>=</span> COUNTER_EXAMPLE
                     <span style='color:#806030; '>.</span>get <span style='color:#005fd2; '>service</span>: <span style='color:#e60000; '>'GiftCardService'</span>
<span style='color:#400000; font-weight:bold; '>end</span>
</pre>

app/views/root/gauge.erb
<% provide(:title, "Gauge") %>
<%= render partial: 'back' %>
<h1>Gauge</h1>
<p>Gauge is a metric that exposes merely an instantaneous value or some snapshot thereof.</p>

<% if @gauge_value > 9000.0 %>
  <h1>It's over 9000!</h1>
<% end %>

<dl>
  <dd><b>@gauge_value = </b> <%= @gauge_value%></dd>
</dl>

<pre style='color:#000000;background:#f1f0f0;'><span style='color:#c34e00; '># Gauge is a metric that exposes merely an instantaneous value or some snapshot thereof.</span>
<span style='color:#400000; font-weight:bold; '>def</span> gauge
  GAUGE_EXAMPLE
    <span style='color:#806030; '>.</span>set<span style='color:#806030; '>(</span><span style='color:#806030; '>{</span><span style='color:#005fd2; '>vehicle</span>: :<span style='color:#005fd2; '>fastest_speed_boat</span><span style='color:#806030; '>}</span><span style='color:#806030; '>,</span> Random<span style='color:#806030; '>.</span>rand <span style='color:#806030; '>*</span> <span style='color:#c00000; '>9000</span> <span style='color:#806030; '>*</span> <span style='color:#c00000; '>2</span><span style='color:#806030; '>)</span>
  @gauge_value <span style='color:#806030; '>=</span> GAUGE_EXAMPLE
                   <span style='color:#806030; '>.</span>get <span style='color:#005fd2; '>vehicle</span>: :<span style='color:#005fd2; '>fastest_speed_boat</span>
<span style='color:#400000; font-weight:bold; '>end</span>
</pre>

app/views/root/histogram.erb
<% provide(:title, "Histogram") %>
<%= render partial: 'back' %>
<h1>Histogram</h1>
<p>A histogram samples observations (usually things like request durations or response sizes) and counts them in configurable buckets. It also provides a sum of all observed values.</p>
<b> New value: <%= @new_value %></b>
<dl>
<% @observations.map do |k, v| %>
  <dt><%= k %></dt>
  <dv><%= v %></dv>
<% end %>
</dl>
<pre style='color:#000000;background:#f1f0f0;'><span style='color:#c34e00; '># A histogram samples observations (usually things like request durations or response sizes) and counts</span>
<span style='color:#c34e00; '># them in configurable buckets. It also provides a sum of all observed values.</span>
<span style='color:#400000; font-weight:bold; '>def</span> histogram
  <span style='color:#c34e00; '># Record a value</span>
  @new_value <span style='color:#806030; '>=</span> Random<span style='color:#806030; '>.</span>rand
  HISTOGRAM_EXAMPLE<span style='color:#806030; '>.</span>observe<span style='color:#806030; '>(</span><span style='color:#806030; '>{</span><span style='color:#005fd2; '>service</span>: :<span style='color:#005fd2; '>jumping_users</span><span style='color:#806030; '>}</span><span style='color:#806030; '>,</span> @new_value<span style='color:#806030; '>)</span>
  <span style='color:#c34e00; '># Retrieve the current bucketed values</span>
  @observations <span style='color:#806030; '>=</span> HISTOGRAM_EXAMPLE<span style='color:#806030; '>.</span>get<span style='color:#806030; '>(</span><span style='color:#005fd2; '>service</span>: :<span style='color:#005fd2; '>jumping_users</span><span style='color:#806030; '>)</span>
<span style='color:#400000; font-weight:bold; '>end</span>
</pre>

app/views/root/index.html.erb
  <% provide(:title, "Prometheus Demo") %>
  <h1>Prometheus Demo</h1>
  <h4>Scraping Endpoint</h4>
  <ul>
    <li>
      <%= link_to "Metrics (Prometheus::Middleware::Exporter + Prometheus::Middleware::Collector)", "/metrics" %>
    </li>
  </ul>
  <h4>Custom Metrics</h4>
  <ul>
    <li>
      <%= link_to "Counter", counter_path %>
    </li>
    <li>
      <%= link_to "Gauge", gauge_path %>
    </li>
    <li>
      <%= link_to "Histogram", histogram_path %>
    </li>
    <li>
      <%= link_to "Summary", summary_path %>
    </li>
  </ul>
  <h4>Support Services</h4>
  <ul>
    <li>
      <%= link_to "Prometheus Dashboard", prometheus_path %>
    </li>
    <li>
      <%= link_to "Grafana Dashboard", grafana_path %>
    </li>
    <li>
      <%= link_to "Alert Manager", alert_manager_path %>
    </li>
    <li>
      <%= link_to "Kubernetes Dashboard", kubernetes_dashboard_path %>
    </li>
  </ul>

app/views/root/summary.erb
<% provide(:title, "Summary") %>
<%= render partial: 'back' %>
<h1>Summary</h1>
<p>Summary, similar to histograms, is an accumulator for samples. It captures Numeric data and provides an efficient percentile calculation mechanism.</p>
<b> New value: <%= @new_value %></b>
<dl>
  <% @observations.map do |k, v| %>
      <dt><%= k %></dt>
      <dv><%= v %></dv>
  <% end %>
</dl>
<pre style='color:#000000;background:#f1f0f0;'><span style='color:#c34e00; '># Summary, similar to histograms, is an accumulator for samples.</span>
<span style='color:#c34e00; '># It captures Numeric data and provides an efficient percentile calculation mechanism.</span>
<span style='color:#400000; font-weight:bold; '>def</span> summary
  @new_value <span style='color:#806030; '>=</span> Random<span style='color:#806030; '>.</span>rand <span style='color:#806030; '>*</span> <span style='color:#c00000; '>100</span>
  SUMMARY_EXAMPLE<span style='color:#806030; '>.</span>observe<span style='color:#806030; '>(</span><span style='color:#806030; '>{</span><span style='color:#005fd2; '>service</span>: :<span style='color:#005fd2; '>test_scores_users</span><span style='color:#806030; '>}</span><span style='color:#806030; '>,</span> @new_value<span style='color:#806030; '>)</span>
  @observations <span style='color:#806030; '>=</span> SUMMARY_EXAMPLE<span style='color:#806030; '>.</span>get<span style='color:#806030; '>(</span><span style='color:#005fd2; '>service</span>: :<span style='color:#005fd2; '>test_scores_users</span><span style='color:#806030; '>)</span>
<span style='color:#400000; font-weight:bold; '>end</span>
</pre>